---
cookie_base_domain: fahrplandatengarten.de
traefik_site_group: prod

icinga2_primary_config_endpoint: "neso.het.fks.de.fahrplandatengarten.de"

icinga2_zones:
  primary:
    endpoints:
      - neso.het.fks.de.fahrplandatengarten.de
      - nereid.ovh.fra.de.fahrplandatengarten.de

icinga2_endpoints:
  neso.het.fks.de.fahrplandatengarten.de:
    host: neso.het.fks.de.fahrplandatengarten.de
  nereid.ovh.fra.de.fahrplandatengarten.de:
    host: nereid.ovh.fra.de.fahrplandatengarten.de

traefik_tls_block: |
  tls:
          certResolver: "le_dns"
          domains:
            - main: "monitoring.fahrplandatengarten.de"
              sans:
                - "*.monitoring.fahrplandatengarten.de"
