---
cookie_base_domain: fahrplandatengarten.de
traefik_site_group: prod

icinga2_primary_config_endpoint: "neso.het.fks.de.fahrplandatengarten.de"

icinga2_zones:
  primary:
    endpoints:
      - neso.het.fks.de.fahrplandatengarten.de
      - nereid.ovh.fra.de.fahrplandatengarten.de
  naiad.ncp.nue.de.fahrplandatengarten.de:
    endpoints:
      - naiad.ncp.nue.de.fahrplandatengarten.de
    parent: primary
# FahrplanDatenGarten
  mars.het.nue.de.fahrplandatengarten.de:
    endpoints:
      - mars.het.nue.de.fahrplandatengarten.de
    parent: primary
# n0emis
  elara.het.nue.de.n0emis.eu:
    endpoints:
      - elara.het.nue.de.n0emis.eu
    parent: primary
  ganymed.het.hel.fi.n0emis.eu:
    endpoints:
      - ganymed.het.hel.fi.n0emis.eu
    parent: primary
  himalia.ion.rhr.de.n0emis.eu:
    endpoints:
      - himalia.ion.rhr.de.n0emis.eu
    parent: primary
  kallisto.int.goe.de.n0emis.eu:
    endpoints:
      - kallisto.int.goe.de.n0emis.eu
    parent: primary
  sinope.int.goe.de.n0emis.eu:
    endpoints:
      - sinope.int.goe.de.n0emis.eu
    parent: primary
  metis.int.goe.de.n0emis.eu:
    endpoints:
      - metis.int.goe.de.n0emis.eu
    parent: primary
# em0lar
  cetus.het.hel.fi.labcode.de:
    endpoints:
      - cetus.het.hel.fi.labcode.de
    parent: primary
  janus.ion.rhr.de.labcode.de:
    endpoints:
      - janus.ion.rhr.de.labcode.de
    parent: primary

icinga2_endpoints:
  neso.het.fks.de.fahrplandatengarten.de:
    host: neso.het.fks.de.fahrplandatengarten.de
  nereid.ovh.fra.de.fahrplandatengarten.de:
    host: nereid.ovh.fra.de.fahrplandatengarten.de
  naiad.ncp.nue.de.fahrplandatengarten.de: {}
# FahrplanDatenGarten
  mars.het.nue.de.fahrplandatengarten.de: {}
# n0emis
  elara.het.nue.de.n0emis.eu: {}
  ganymed.het.hel.fi.n0emis.eu: {}
  himalia.ion.rhr.de.n0emis.eu: {}
  kallisto.int.goe.de.n0emis.eu: {}
  sinope.int.goe.de.n0emis.eu: {}
  metis.int.goe.de.n0emis.eu: {}
# em0lar
  cetus.het.hel.fi.labcode.de: {}
  janus.ion.rhr.de.labcode.de: {}

traefik_tls_block: |
  tls:
          certResolver: "le_dns"
          domains:
            - main: "monitoring.fahrplandatengarten.de"
              sans:
                - "*.monitoring.fahrplandatengarten.de"
