---
- name: Check IDO schema version in MySQL
  command:
    mysql
    -h {{ icinga2_ido_host|quote }}
    -u {{ icinga2_ido_user|quote }}
    -p{{ icinga2_ido_password|quote }}
    {{ icinga2_ido_name|quote }}
    -Ns -e "SHOW TABLES LIKE 'icinga_dbversion'"
  changed_when: False
  register: table_exists

- name: Import icinga2 schema
  mysql_db:
    login_host: "{{ icinga2_ido_host }}"
    login_port: "{{ icinga2_ido_port }}"
    login_user: "{{ icinga2_ido_user }}"
    login_password: "{{ icinga2_ido_password }}"
    name: "{{ icinga2_ido_name }}"
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
    state: import
  ignore_errors: yes
  run_once: true
  when: table_exists.stdout == ""
