---
- name: Install icinga2 dependencies
  apt:
    name: gnupg
    state: present

- name: Add icinga2 repo key
  apt_key:
    url: "{{ icinga2_apt_repo.gpgkey }}"
    state: present

- name: Add icinga2 repository
  apt_repository:
    repo: "{{ icinga2_apt_repo.repo }}"
    state: present
    update_cache: yes

- name: Install icinga2 basic packages
  apt:
    name: "{{ icinga2_packages_debian }}"
    state: "present"

- name: Import icinga2 schema
  import_tasks: ido-mysql.yml
  when: ansible_fqdn == icinga2_primary_config_endpoint

- name: Set up the host
  command: "icinga2 node setup --master --disable-confd --zone primary --cn {{ ansible_fqdn }}"
  args:
    creates: "/var/lib/icinga2/certs/{{ ansible_fqdn }}.crt"
  notify: restart icinga2
  when: ansible_fqdn == icinga2_primary_config_endpoint

- include_tasks: "add-host.yml"
  when: ansible_fqdn != icinga2_primary_config_endpoint

- name: Set up the icinga2 api
  command: "icinga2 api setup"
  register: api_setup
  changed_when: "'Generating new CSR' in api_setup.stdout"
  notify: restart icinga2
  when: ansible_fqdn != icinga2_primary_config_endpoint

- name: install opsgenie
  import_tasks: opsgenie.yml

- name: Enable required icinga features
  command: "icinga2 feature enable {{ item }}"
  register: enable_feature
  changed_when: "'Enabling feature' in enable_feature.stdout"
  loop: "{{ icinga2_features }}"
  notify: restart icinga2

- name: Copy Icinga config files
  template:
    dest: "/etc/icinga2/{{ item }}"
    src: "{{ item }}.j2"
  loop:
    - "features-available/ido-mysql.conf"
    - "features-available/graphite.conf"
    - "features-available/api.conf"
    - "conf.d/api-users.conf"
    - "zones.conf"
  notify: restart icinga2

- name: Create zones.d directories
  file:
    state: directory
    path: "/etc/icinga2/zones.d/{{ item.path  }}"
  with_filetree: ../templates/icinga2/zones.d
  when: ansible_fqdn == icinga2_primary_config_endpoint and item.state == 'directory'

- name: Copy zones.d files
  template:
    src: "{{ item.src }}"
    dest: "/etc/icinga2/zones.d/{{ item.path | replace('.j2', '') }}"
  with_filetree: ../templates/icinga2/zones.d
  notify: restart icinga2
  when: ansible_fqdn == icinga2_primary_config_endpoint and item.state == 'file'

- name: Fix ping permissions
  file:
    dest: /bin/ping
    mode: u+s
