---
icinga2_apt_repo:
  repo: "deb http://packages.icinga.com/debian icinga-{{ ansible_distribution_release }} main"
  gpgkey: http://packages.icinga.com/icinga.key

icinga2_packages_debian:
  - icinga2
  - icinga2-ido-mysql
  - monitoring-plugins
  - bash-completion
  - vim-icinga2
  - vim

icinga2_features:
  - ido-mysql
  - api
