---
- name: restart carbon-cache
  service:
    name: "carbon-cache"
    state: restarted

- name: restart carbon-relay
  service:
    name: "carbon-relay@default"
    state: restarted

- name: restart uwsgi
  service:
    name: "uwsgi"
    state: "restarted"
