---
- name: Download and extract authelia
  unarchive:
    src: "{{ authelia_download_url }}"
    dest: "{{ authelia_binary_path }}"
    remote_src: yes

- name: Make sure authelia config-dir exists
  file:
    path: "{{ authelia_config_path }}"
    state: directory

- name: Copy authelia config file
  template:
    src: "config.yml.j2"
    dest: "{{ authelia_config_path }}/config.yml"
  notify: restart authelia

- name: Copy systemd service
  template:
    src: "authelia.service.j2"
    dest: "/etc/systemd/system/authelia.service"
  notify: restart authelia

- name: Make sure authelia is enabled and started
  service:
    name: "authelia"
    state: started
    enabled: yes
    daemon-reload: yes
