---
- name: restart icinga2
  command: "icinga2 daemon -C"
  notify: restart icinga2 service

- name: restart icinga2 service
  service:
    name: icinga2
    state: restarted

- name: restart oec
  service:
    name: oec
    state: restarted
