openldap_debian_packages:
  - slapd
  - ldap-utils

openldap_org: "monitoring"
openldap_tld: "fdg"
openldap_admin_bind: "cn=admin,dc={{ openldap_org }},dc={{ openldap_tld }}"

openldap_config: true
openldap_populate: false
openldap_populate: true
openldap_posixgroups: []
openldap_users: []
openldap_organizationalunits:
  - People
  - Groups

openldap_overlays_and_acls:
  - name: general
    ldifs:
      - path: memberof.ldif
        action: add

authelia_db_name: authelia
authelia_db_user: authelia
