mysql_root_username: "root"
mysql_root_password_update: false

galera_cluster_bind_address: "0.0.0.0"
galera_wsrep_cluster_name: "monitoring-cluster"
galera_wsrep_cluster_address: "{% for host in ansible_play_batch %}{{ hostvars[host].galera_wsrep_node_address }}{% if loop.index != loop.length %},{% endif %}{% endfor %}"
galera_wsrep_node_name: "{{ ansible_fqdn }}"

mysql_users:
  - name: "{{ icingaweb2_db_user }}"
    password: "{{ icingaweb2_db_password }}"
    priv: "{{ icingaweb2_db_name }}.*:ALL"
  - name: "{{ icinga2_ido_user }}"
    password: "{{ icinga2_ido_password }}"
    priv: "{{ icinga2_ido_name }}.*:ALL"
  - name: "{{ authelia_db_user }}"
    password: "{{ authelia_db_password }}"
    priv: "{{ authelia_db_name }}.*:ALL"

mysql_databases:
  - name: "{{ icingaweb2_db_name }}"
  - name: "{{ icinga2_ido_name }}"
  - name: "{{ authelia_db_name }}"
