---
prometheus_web_listen_address: "127.0.0.1:9090"
prometheus_web_external_url: "/prometheus"

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets:
        - "{{ prometheus_web_listen_address }}"
  - job_name: "synapse"
    metrics_path: "/_synapse/metrics"
    scheme: https
    static_configs:
      - targets:
        - "matrix.noemis.me"
        - "matrix.labcode.de"
  - job_name: "traefik"
    metrics_path: "/metrics/prometheus"
    scheme: https
    static_configs:
      - targets:
        - "dione.int.sig.de.labcode.de"
        - "mars.het.nue.de.fahrplandatengarten.de"
