---
prometheus_web_listen_address: "127.0.0.1:9090"
prometheus_web_external_url: "/prometheus"

prometheus_global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets:
        - "{{ prometheus_web_listen_address }}"
  - job_name: "synapse"
    metrics_path: "/_synapse/metrics"
    scheme: https
    static_configs:
      - targets:
        - "matrix.noemis.me"
        - "matrix.labcode.de"
        - "matrix.chaos.jetzt"
        - "matrix.dev.chaos.jetzt"
  - job_name: "traefik"
    metrics_path: "/metrics/prometheus"
    scheme: https
    static_configs:
      - targets:
        - "mars.het.nue.de.fahrplandatengarten.de"
        - "elara.het.nue.de.n0emis.eu"
        - "sinope.int.goe.de.n0emis.eu"
  - job_name: "keycloak"
    metrics_path: "/auth/realms/master/metrics"
    scheme: https
    static_configs:
      - targets:
          - "auth.n0emis.eu"
          - "sso.chaos.jetzt"
          - "sso.dev.chaos.jetzt"
  - job_name: "telegraf"
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "localhost:9273"
  - job_name: "corona"
    metrics_path: "/metrics"
    scrape_interval: "1h"
    static_configs:
      - targets:
        - "localhost:9001"
        - "localhost:9002"
  - job_name: minio
    bearer_token: "{{ minio_n0emis_eu_bearer }}"
    metrics_path: /minio/prometheus/metrics
    scheme: https
    static_configs:
      - targets: [minio.n0emis.eu]
  - job_name: powerdns
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "ns.n0emis.eu:8082"
        - "ns2.n0emis.eu:8082"
        - "ns3.n0emis.eu:8082"
  - job_name: openwrt
    metrics_path: "/metrics"
    scheme: https
    basic_auth: "{{ openwrt_metrics_basic_auth }}"
    static_configs:
      - targets:
        - "atlas.int.sig.de.labcode.de"
        - "io-metrics.int.goe.de.n0emis.eu"
  - job_name: caddy
    metrics_path: "/metrics"
    scheme: https
    basic_auth: "{{ caddy_metrics_basic_auth }}"
    static_configs:
      - targets:
        - "titan.int.sig.de.labcode.de"
        - "pasiphae.int.goe.de.n0emis.eu"
