---
traefik_version: "v2.3.0"

traefik_base_path: "/var/lib/traefik"
traefik_config_directory: "/etc/traefik"

traefik_middlewares_https_redirect_enable: yes

traefik_dynamic_config_files_paths:
  - "../templates/traefik/dynamic/*"
