---
- hosts: all
  become: yes
  roles:
    - n0emis.base
    - gantsign.oh-my-zsh
  tags: base

- hosts: primary
  become: yes
  roles:
    - n0emis.wireguard
  tags:
    - wireguard
    - wg

- hosts: primary
  become: yes
  roles:
    - mariadb-galera-cluster
  tags: db

- hosts: primary
  become: yes
  roles:
    - geerlingguy.php
  tags: php

- hosts: primary
  become: yes
  roles:
    - geerlingguy.nginx
  tags: nginx

- hosts: primary
  become: yes
  roles:
    - em0lar.traefik
  tags: traefik

- hosts: primary
  become: yes
  roles:
    - geerlingguy.redis
    - dynomite
  tags: redis, auth

- hosts: primary
  become: yes
  roles:
    - mrlesmithjr.openldap
  tags: ldap, auth

- hosts: primary
  become: yes
  roles:
    - authelia
  tags: authelia, auth

- hosts: primary
  become: yes
  roles:
    - graphite
  tags: graphite

- hosts: primary_icinga
  become: yes
  roles:
    - icinga2-primary
  tags: icinga

- hosts: primary_icinga
  become: yes
  roles:
    - icingaweb2
  tags: icingaweb,web

- hosts: primary
  become: yes
  serial:
    - 1
    - "100%"
  roles:
    - cloudalchemy.grafana
  tags: grafana
