---
- hosts: all
  become: yes
  roles:
    - n0emis.base
    - gantsign.oh-my-zsh
  tags: base

- hosts: primary
  become: yes
  roles:
    - mariadb-galera-cluster
  tags: db

- hosts: primary
  become: yes
  roles:
    - geerlingguy.php
    - geerlingguy.nginx
  tags: php

- hosts: primary
  become: yes
  roles:
    - icinga2-primary
  tags: icinga

- hosts: primary
  become: yes
  roles:
    - icingaweb2
  tags: icingaweb,web
