---
- hosts: all
  become: yes
  roles:
    - n0emis.base
    - gantsign.oh-my-zsh
    - jnv.unattended-upgrades
  tags: base

- hosts: primary
  become: yes
  roles:
    - geerlingguy.mysql
  tags: db

- hosts: primary
  become: yes
  roles:
    - geerlingguy.nginx
  tags: nginx

- hosts: primary_icinga
  become: yes
  roles:
    - geerlingguy.php
  tags: php

- hosts: primary
  become: yes
  serial:
    - 1
  roles:
    - em0lar.traefik
  tasks:
    - name: Copy acme-dns config file
      template:
        src: "../templates/traefik/dns-acme.json.j2"
        dest: "{{ traefik_acme_dns_file }}"
        owner: "{{ traefik_user }}"
        group: "{{ traefik_group }}"
      notify: restart traefik service
  tags: traefik

- hosts: primary
  become: yes
  roles:
    - geerlingguy.redis
    - dynomite
  tags: redis, auth

- hosts: primary
  become: yes
  roles:
    - mrlesmithjr.openldap
  tags: ldap, auth

- hosts: primary
  become: yes
  roles:
    - authelia
  tags: authelia, auth

- hosts: primary
  become: yes
  roles:
    - graphite
  tags: graphite

- hosts: primary_icinga
  become: yes
  roles:
    - icinga2-primary
  tags: icinga

- hosts: agents,primary_icinga
  become: yes
  roles:
    - fahrplandatengarten.icinga
  tags: icinga-agent

- hosts: primary_icinga
  become: yes
  roles:
    - icingaweb2
  tags: icingaweb,web

- hosts: primary_prometheus
  become: yes
  roles:
    - cloudalchemy.prometheus
  tags: prometheus

- hosts: primary_prometheus
  become: yes
  roles:
    - dj-wasabi.telegraf
  tags: telegraf

- hosts: primary
  become: yes
  serial:
    - 1
    - "100%"
  roles:
    - cloudalchemy.grafana
  tags: grafana
